name: linkpred
channels:
  - defaults
dependencies:
  - python=3.9
  - mamba
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.6
  - ca-certificates
  - certifi
  - openssl
  - snakemake
  - graph-tool
  - scikit-learn
  - numpy==1.23.5
  - numba
  - scipy
  - pandas
  - networkx
  - seaborn
  - matplotlib
  - gensim
  - ipykernel
  - tqdm
  - black
  - stellargraph
