name: linkpred 
channels:
  - bioconda
  - pytorch
  - conda-forge
  - stellargraph
  - pyg 
  - defaults
dependencies:
  - python=3.9
  - pytorch 
  - graph-tool 
  - scikit-learn 
  - numpy 
  - numba 
  - scipy 
  - pandas 
  - networkx 
  - gensim 
  - faiss-gpu 
  - umap-learn 
  - pyg 
  - pytorch 
  - torchvision 
  - torchaudio 
  - stellargraph
