name: mylinkpred
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cuda-version=12.1
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - snakemake
  - graph-tool
  - scikit-learn
  - numpy==1.23.5
  - numba
  - scipy==1.10.1
  - pandas
  - polars
  - networkx
  - seaborn
  - matplotlib
  - gensim
  - ipykernel
  - tqdm
  - black
  - faiss-gpu
  - pyg
  - pytorch-sparse
  - python-igraph

