baseURL = 'https://skojaku.github.io/'
languageCode = 'en-us'
title = 'Implicit degree bias in the link prediction task'
theme = "nostyleplease"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
